{{ if .Values.externalAccess.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: default
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: jnlp
      port: 50000
      targetPort: 50000
{{ end }}

# TODO: Attach to NFS server possibly. 
# TODO: Bind jenkinses to a single AZ
